# generated by appcreator
import django_filters
from django import forms

from dal import autocomplete

from . models import (
    Dataset,
    Example
)


class DatasetListFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Dataset._meta.get_field('name').help_text,
        label=Dataset._meta.get_field('name').verbose_name
    )
    description = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Dataset._meta.get_field('description').help_text,
        label=Dataset._meta.get_field('description').verbose_name
    )

    class Meta:
        model = Dataset
        fields = [
            'id',
            'name',
            'created',
            'session',
            'description',
            ]


class ExampleListFilter(django_filters.FilterSet):

    class Meta:
        model = Example
        fields = [
            'id',
            'input_hash',
            'task_hash',
            'link',
            ]
