# generated by appcreator
import django_tables2 as tables
from django_tables2.utils import A

from browsing.browsing_utils import MergeColumn
from . models import (
    Dataset,
    Example
)


class DatasetTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Dataset
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ExampleTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')
    link = tables.columns.ManyToManyColumn()

    class Meta:
        model = Example
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}
