# generated by appcreator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from . filters import *
from . forms import *
from . tables import *
from . models import (
    Dataset,
    NerSample,
    Example
)
from browsing.browsing_utils import (
    GenericListView, BaseCreateView, BaseUpdateView, BaseDetailView
)


class NerSampleListView(GenericListView):

    model = NerSample
    filter_class = NerSampleListFilter
    formhelper_class = NerSampleFilterFormHelper
    table_class = NerSampleTable
    init_columns = [
        'id', 'text'
    ]
    enable_merge = False


class NerSampleDetailView(BaseDetailView):

    model = NerSample
    template_name = 'myprodigy/generic_detail.html'


class NerSampleCreate(BaseCreateView):

    model = NerSample
    form_class = NerSampleForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NerSampleCreate, self).dispatch(*args, **kwargs)


class NerSampleUpdate(BaseUpdateView):

    model = NerSample
    form_class = NerSampleForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NerSampleUpdate, self).dispatch(*args, **kwargs)


class NerSampleDelete(DeleteView):
    model = NerSample
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('myprodigy:nersample_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NerSampleDelete, self).dispatch(*args, **kwargs)


class DatasetListView(GenericListView):

    model = Dataset
    filter_class = DatasetListFilter
    formhelper_class = DatasetFilterFormHelper
    table_class = DatasetTable
    init_columns = [
        'id', 'name',
    ]
    enable_merge = False


class DatasetDetailView(BaseDetailView):

    model = Dataset
    template_name = 'myprodigy/generic_detail.html'


class DatasetCreate(BaseCreateView):

    model = Dataset
    form_class = DatasetForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DatasetCreate, self).dispatch(*args, **kwargs)


class DatasetUpdate(BaseUpdateView):

    model = Dataset
    form_class = DatasetForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DatasetUpdate, self).dispatch(*args, **kwargs)


class DatasetDelete(DeleteView):
    model = Dataset
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('myprodigy:dataset_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DatasetDelete, self).dispatch(*args, **kwargs)


class ExampleListView(GenericListView):

    model = Example
    filter_class = ExampleListFilter
    formhelper_class = ExampleFilterFormHelper
    table_class = ExampleTable
    init_columns = [
        'id', 'False',
    ]
    enable_merge = True


class ExampleDetailView(BaseDetailView):

    model = Example
    template_name = 'myprodigy/generic_detail.html'


class ExampleCreate(BaseCreateView):

    model = Example
    form_class = ExampleForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ExampleCreate, self).dispatch(*args, **kwargs)


class ExampleUpdate(BaseUpdateView):

    model = Example
    form_class = ExampleForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ExampleUpdate, self).dispatch(*args, **kwargs)


class ExampleDelete(DeleteView):
    model = Example
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('myprodigy:example_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ExampleDelete, self).dispatch(*args, **kwargs)
