# Generated by Django 3.1.3 on 2020-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprodigy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodigyserver',
            name='auto_start',
            field=models.BooleanField(default=True),
        ),
    ]
