# Generated by Django 3.1.1 on 2020-12-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprodigy', '0003_nersample_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nersample',
            name='is_public',
        ),
        migrations.AddField(
            model_name='nerdataset',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Should the data related to this dataset be public', verbose_name='pubic'),
        ),
    ]
