# Generated by Django 3.1.1 on 2020-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprodigy', '0004_auto_20201201_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerdataset',
            name='pw',
            field=models.CharField(default='annotate2020', help_text='Password used for authorisation of Prodigy Server', max_length=250, verbose_name='Password for Prodigy-Server'),
        ),
    ]
