# Generated by Django 3.1.1 on 2020-12-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprodigy', '0005_nerdataset_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerdataset',
            name='basic_auth_user',
            field=models.CharField(default='no_basic_auth_username_set', help_text='Password used for authorisation of Prodigy Server', max_length=250, verbose_name='Username for basic authentication'),
        ),
        migrations.AddField(
            model_name='nerdataset',
            name='reverse_proxy',
            field=models.CharField(blank=True, help_text='Needs to be set up from SysAdmin.', max_length=250, null=True, verbose_name='Reverse Proxy for Prodigy Server'),
        ),
        migrations.AlterField(
            model_name='nerdataset',
            name='pw',
            field=models.CharField(default='no_basic_auth_pw_set', help_text='Password used for authorisation of Prodigy Server', max_length=250, verbose_name='Basic auth password'),
        ),
    ]
