# Generated by Django 3.1.1 on 2020-12-05 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprodigy', '0006_auto_20201201_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerdataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nerdataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nersample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nersample',
            name='orig_id',
            field=models.BigIntegerField(blank=True, help_text='The ID of the original Prodigy Example ID', null=True, verbose_name='Example ID'),
        ),
        migrations.AddField(
            model_name='nersample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
