# Generated by Django 3.1.1 on 2020-12-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprodigy', '0007_auto_20201205_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nersample',
            name='orig_id',
        ),
    ]
